### ISSUE TITLE
When train end2end, this maybe confused.

### ISSUE THREAD

**Issue by U-uU** [invoker-LL/WSI-finetuning#4]
# temp_split=i
        temp_split = 0 # to avoid validation data leakage

https://github.com/invoker-LL/WSI-finetuning/blob/e1c6972a3a1fa47b2e3497fb042cbc8a6372431d/train_end2end.py#L39C8-L40C58

**Comment by invoker-LL** [comment]
The model is trained with 5 folds train-val splits in stage-1, but in this repo we only use fold-0 to generate top-k, if you use this top-k to train stage-2 for fold-1~4, there must be some small data leakage from val to train (e.g. some wsi data in val during fold-0 may be split into train during fold-1).
So, there are 2 solutions: 1) generate different top-k for each fold using their own train-val split stage-1 model, but this may need more memory and computation. 2) use only fold-0 but with 5 different random seeds for both stage-1&2.
Remember that the 5-folds are used to get more stable averaged results, reported in our paper (the problem is caused by the limited samples num of WSIs). However, we find that above 2 solutions get similar stable results, so I recommend you use latter one, which is faster and efficient.
