### ISSUE TITLE
Inquiry about Missing Slides when Patching

### ISSUE THREAD

**Issue by bryanwong17** [invoker-LL/WSI-finetuning#7]
Hi, I tried following your code to create patches by using `bash create_patches.sh`. However, there are two missing slides (normal_027 and normal_045), and as a result, I could only get 397 instead of 399 on Camelyon16 dataset. Do you perhaps know why?

Thank you!

**Comment by invoker-LL** [comment]
These 2 slides are of very few tissue areas, thus may be filtered by operations (like otsu) during pre-processing.
But the otsu is useful during reproduce the result of CLAM.

**Comment by bryanwong17** [comment]
So do you have any suggestions in order to reproduce the result? how did you deal with this issue?

**Comment by invoker-LL** [comment]
You can just omit these 2 slides during training, which will get about similar AUC score compared to CLAM. 
But if the OTSU is not included during preprocess, I can only get an AUC score of 0.82-0.83.  (I am not quite sure about the details in their experiments either, or you may try the preprocess in [DTFD](https://github.com/hrzhang1123/DTFD-MIL)?)
Above results are mainly caused by the weak embedding of ImageNet pretraining, if your use pretraining embedding like [lunit](https://lunit-io.github.io/research/publications/pathology_ssl/), which may not be a question. 
Though I think there will also be some improvement using our fine-tuning based on lunit embedding, but Camelyon-16 may easily meet its upper-bound, like an AUC of 0.96-0.97, thus the improvement may be slightly.

**Comment by bryanwong17** [comment]
Got it. Thank you for your help!
